# Generated by Django 6.0 on 2025-12-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ticket_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('donation', 'Donation')], default='free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('quantity_available', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('sale_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('sale_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('min_per_order', models.PositiveIntegerField(default=1)),
                ('max_per_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist'), ('attended', 'Attended')], default='pending', max_length=20)),
                ('registration_datetime', models.DateTimeField(auto_now_add=True)),
                ('confirmation_datetime', models.DateTimeField(blank=True, null=True)),
                ('cancellation_datetime', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes from attendee')),
                ('dietary_requirements', models.CharField(blank=True, max_length=200)),
                ('special_requests', models.TextField(blank=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('check_in_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_datetime'],
                'indexes': [models.Index(fields=['event', 'status'], name='registratio_event_i_246b4a_idx'), models.Index(fields=['user', 'status'], name='registratio_user_id_e3aac6_idx')],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
